/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.MetodosConexionBD1;
import Controlador.Controlador_FRM_MantenimientoEstudiantes;
import javax.swing.JOptionPane;

/**
 *
 * @author JorgeIgnacioElizondoAlvarado
 */
public class FRM_MantenimientoEstudiantes extends javax.swing.JFrame {

    //Se declaran las variables
    String sistemaInfo = "";
    
    //Referencias de clases
    public Controlador_FRM_MantenimientoEstudiantes controlador_FRM_MantenimientoEstudiantes;
    MetodosConexionBD1 conexionBD1;
    
    public FRM_MantenimientoEstudiantes(String sistemaInfo, MetodosConexionBD1 conexionBD1) {
        initComponents();
        
        setVisible(false);
        this.conexionBD1 = conexionBD1;
        this.sistemaInfo = sistemaInfo;
        controlador_FRM_MantenimientoEstudiantes=new Controlador_FRM_MantenimientoEstudiantes(this, this.sistemaInfo, this.conexionBD1);
        gUI_Botones1.agregarEventos(controlador_FRM_MantenimientoEstudiantes);
        this.gUI_InformacionEstudiantes1.agregarEventoConsulta(controlador_FRM_MantenimientoEstudiantes);
        estadoInicialBotones();
        estadoInicialCampos();
    }
    
    public String[] devolverInformacion() {
        return this.gUI_InformacionEstudiantes1.devolverInformacion();
    }
    public String devolverCedula() {
        return this.gUI_InformacionEstudiantes1.devolverCedula();
    
    }
    public void mostrarInformacion(String arreglo[]) {
        this.gUI_InformacionEstudiantes1.mostrarInformacion(arreglo);
    }
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }
    public void limpiarCampos() {
        this.gUI_InformacionEstudiantes1.limpiarCampos();
    }
    public void estadoInicialBotones() {
        this.gUI_Botones1.estadoInicialBotones();
    }
    public void estadoInicialCampos() {
        this.gUI_InformacionEstudiantes1.estadoInicialCampos();
    }
    public void habilitarBotones() {
        this.gUI_Botones1.habilitarBotones();
    }
    public void administrarCampos() {
        this.gUI_InformacionEstudiantes1.administrarCampos();
    }
    public void habilitarAgregar() {
        this.gUI_Botones1.habilitarAgregar();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_Botones1 = new Vista.GUI_Botones2();
        gUI_InformacionEstudiantes1 = new Vista.GUI_InformacionEstudiantes();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gUI_InformacionEstudiantes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gUI_InformacionEstudiantes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
    Cuando FRM_MantenimientoEstudiantes se cierra se ejecuta este evento
    */
    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        
        controlador_FRM_MantenimientoEstudiantes.metodosEstudiantes.escribirInformacionArchivo();
        
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones2 gUI_Botones1;
    private Vista.GUI_InformacionEstudiantes gUI_InformacionEstudiantes1;
    // End of variables declaration//GEN-END:variables
}
