/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_MantenimientoCursos;
import Modelo.MetodosConexionBD1;
import javax.swing.JOptionPane;

/**
 *
 * @author JorgeIgnacioElizondoAlvarado
 */
public class FRM_MantenimientoCursos extends javax.swing.JFrame {

    //Se declaran las variables
    String sistemaInfo = "";
    
    //Referencias
    public Controlador_FRM_MantenimientoCursos controlador;
    MetodosConexionBD1 conexionBD1;
    
    //Constructor de la clase
    public FRM_MantenimientoCursos(String sistemaInfo, MetodosConexionBD1 conexionBD1) {
        
        initComponents();
        this.conexionBD1 = conexionBD1;
        this.sistemaInfo = sistemaInfo;
        controlador = new Controlador_FRM_MantenimientoCursos(this, this.sistemaInfo, this.conexionBD1);
        this.gUI_Botones1.agregarEventos(controlador);
        this.gUI_InformacionCursos2.agregarFuncionConsultaRapida(controlador);
        estadoInicialBotones();
        estadoInicialCampos();
        
    }//Fin del constructor de la clase
    
    
    public String[] devolverInformacion(){
        return this.gUI_InformacionCursos2.devolverInformacion();
    }
    public String devolverSigla(){
        return this.gUI_InformacionCursos2.devolverSigla();
    }
    public void mostrarInformacion(String arreglo[]){
        this.gUI_InformacionCursos2.mostrarInformacion(arreglo);
    }
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }
    public void limpiarCampos() {
        this.gUI_InformacionCursos2.limpiarCampos();
    }
    public void habilitarCampos() {
        this.gUI_InformacionCursos2.habilitarCampos();
    }
    public void habilitarAgregar() {
        this.gUI_Botones1.habilitarAgregar();
    }
    public void estadoInicialBotones() {
        this.gUI_Botones1.estadoInicialBotones();
    }
    public void estadoInicialCampos() {
        this.gUI_InformacionCursos2.estadoInicialCampos();
    }
    public void habilitarBotones() {
        this.gUI_Botones1.habilitarBotones();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        gUI_Botones1 = new Vista.GUI_Botones2();
        gUI_InformacionCursos2 = new Vista.GUI_InformacionCursos();
        jLabel1 = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gUI_Botones1.setOpaque(false);
        getContentPane().add(gUI_Botones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        gUI_InformacionCursos2.setOpaque(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gUI_InformacionCursos2, org.jdesktop.beansbinding.ELProperty.create("${background}"), gUI_InformacionCursos2, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        getContentPane().add(gUI_InformacionCursos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoLogin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        controlador.metodosCursos.escribirInformacionArchivo();
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones2 gUI_Botones1;
    private Vista.GUI_InformacionCursos gUI_InformacionCursos2;
    private javax.swing.JLabel jLabel1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
