/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_MantenimientoUsuarios;
import Modelo.MetodosConexionBD1;
import Modelo.MetodosUsuario;
import Vista.FRM_LoginUsuario;
import javax.swing.JOptionPane;
/**
 *
 * @author JorgeIgnacioElizondoAlvarado
 */
public class FRM_MantenimientoUsuarios extends javax.swing.JFrame {

    //Se declaran las variables
    String sistemaInfo = "";
    
    //Referencia
    public Controlador_FRM_MantenimientoUsuarios controlador_FRM_MantenimientoUsuarios;
    FRM_LoginUsuario fRM_LoginUsuario;
    MetodosConexionBD1 conexionBD1;
    MetodosUsuario mu;
    
    public FRM_MantenimientoUsuarios(String sistemaInfo, MetodosConexionBD1 conexionBD1) {
        
        initComponents();
        this.setLocation(250, 100);
        this.conexionBD1 = conexionBD1;
        this.sistemaInfo = sistemaInfo;
        this.fRM_LoginUsuario = fRM_LoginUsuario;
        controlador_FRM_MantenimientoUsuarios = new Controlador_FRM_MantenimientoUsuarios(this, this.sistemaInfo, this.conexionBD1);
        this.gUI_Botones1.agregarEventos(controlador_FRM_MantenimientoUsuarios);            
        this.gUI_Botones1.estadoInicialBotones();
        this.gUI_InformacionUsuario1.estadoInicialCampos();
        this.gUI_InformacionUsuario1.agregarEventoConsultaRapida(controlador_FRM_MantenimientoUsuarios);
    }
    
    /*
    
    */
    public String[] devolverInfoUsuario()
    {
        return this.gUI_InformacionUsuario1.devolverInfoUsuario();
    }
    
    public String devolverIdUsuario() {
        return this.gUI_InformacionUsuario1.devolverIdUsuario();
    }
    
    
    
    /*
    
    */
    public void estadoInicialCampos() {
        this.gUI_InformacionUsuario1.estadoInicialCampos();
    }
    
    /*
    
    */
    public void administrarCampos() {
        this.gUI_InformacionUsuario1.administrarCampos();
    }
    
    /*
    
    */
    public void mostrarInfoPantalla(String arregloUsuario[])
    {
        this.gUI_InformacionUsuario1.mostrarInfoPantalla(arregloUsuario);
    }
    
    /*
    
    */
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }
    
    /*
    
    */
    public void limpiarCampos()
    {
        this.gUI_InformacionUsuario1.limpiarCampos();
    }
    
    public void habilitarBotones() {
        this.gUI_Botones1.habilitarBotones();
    }
    
    public void habilitarAgregar() {
        this.gUI_Botones1.habilitarAgregar();
    }
    
    public void estadoInicialBotones() {
        this.gUI_Botones1.estadoInicialBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_Botones1 = new Vista.GUI_Botones2();
        gUI_InformacionUsuario1 = new Vista.GUI_InformacionUsuario();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(450, 350));
        setPreferredSize(new java.awt.Dimension(450, 350));
        setResizable(false);
        setSize(new java.awt.Dimension(450, 350));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(null);

        gUI_Botones1.setOpaque(false);
        getContentPane().add(gUI_Botones1);
        gUI_Botones1.setBounds(10, 190, 294, 73);

        gUI_InformacionUsuario1.setOpaque(false);
        getContentPane().add(gUI_InformacionUsuario1);
        gUI_InformacionUsuario1.setBounds(0, 0, 449, 176);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoUsuario.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
        controlador_FRM_MantenimientoUsuarios.metodosUsuario.escribirInformacionArchivo();
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones2 gUI_Botones1;
    private Vista.GUI_InformacionUsuario gUI_InformacionUsuario1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
