/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.Controlador_FRM_LoginUsuario;
import Vista.FRM_MantenimientoUsuarios;
import Modelo.MetodosConexionBD1;
import Modelo.MetodosUsuario;
import Modelo.Manejador_Ventanas;

/**
 *
 * @author JorgeIgnacio
 */
public class FRM_LoginUsuario extends javax.swing.JFrame {

    //Se declaran las variables de la clase
    String sistemaInformacion = "";
    
    //Referencias
    FRM_MenuPrincipal fRM_MenuPrincipal;
    FRM_MantenimientoUsuarios fRM_MantenimientoUsuarios;
    MetodosConexionBD1 metodosConexionBD1;
    Controlador_FRM_LoginUsuario controlador_FRM_LoginUsuario;
    MetodosUsuario metodosUsuario;
    Manejador_Ventanas manejador_Ventanas;
    
    
    
    /**
     * Constructor de la clase
     */
    public FRM_LoginUsuario(String sistemaInfo, MetodosConexionBD1 metodosConexionBD1, FRM_MantenimientoUsuarios fRM_MantenimientoUsuarios, Manejador_Ventanas manejador_Ventanas) {
        
        initComponents();
        setLocation(450, 200);
        this.manejador_Ventanas = manejador_Ventanas;
        this.fRM_MantenimientoUsuarios = fRM_MantenimientoUsuarios;
        this.metodosConexionBD1 = metodosConexionBD1;
        this.sistemaInformacion = sistemaInfo;
        
        controlador_FRM_LoginUsuario = new Controlador_FRM_LoginUsuario(this, this.sistemaInformacion, this.metodosConexionBD1, this.metodosUsuario, this.fRM_MantenimientoUsuarios, this.manejador_Ventanas);
        agregarEventoBtn();
        
    }
    
    
    
    /*
    Agrega las funciones al botón
    */
    public void agregarEventoBtn() {
        this.jB_Entrar.addActionListener(controlador_FRM_LoginUsuario);
    }
    
    /*
    Método que extrae los datos de los campos
    */
    public String[] getInfoLogin() {
        
        String arrayInfo[] = new String[2];
        
        char[] arrayC = this.jP_Contrasena.getPassword();
        String pass = new String(arrayC);
        
        arrayInfo[0] = this.jT_Usuario.getText();
        arrayInfo[1] = pass;
        
        return arrayInfo;
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_Entrar = new javax.swing.JButton();
        jL_Usuario = new javax.swing.JLabel();
        jL_Contrasena = new javax.swing.JLabel();
        jT_Usuario = new javax.swing.JTextField();
        jP_Contrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jB_Entrar.setText("Entrar al Sistema");
        jB_Entrar.setActionCommand("Entrar");

        jL_Usuario.setText("Usuario");

        jL_Contrasena.setText("Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jB_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_Contrasena)
                            .addComponent(jL_Usuario))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jP_Contrasena)
                            .addComponent(jT_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Usuario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jP_Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Contrasena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jB_Entrar)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Entrar;
    private javax.swing.JLabel jL_Contrasena;
    private javax.swing.JLabel jL_Usuario;
    private javax.swing.JPasswordField jP_Contrasena;
    private javax.swing.JTextField jT_Usuario;
    // End of variables declaration//GEN-END:variables
}
