/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.Controlador_FRM_LoginUsuario;
import Vista.FRM_MantenimientoUsuarios;
import Modelo.MetodosConexionBD1;
import Modelo.MetodosUsuario;
import Modelo.XML_Usuarios;
import Modelo.Manejador_Ventanas;
import javax.swing.JOptionPane;

/**
 *
 * @author JorgeIgnacio
 */
public class FRM_LoginUsuario extends javax.swing.JFrame {

    //Se declaran las variables de la clase
    String sistemaInformacion = "";
    
    //Referencias
    FRM_MantenimientoUsuarios fRM_MantenimientoUsuarios;
    MetodosConexionBD1 metodosConexionBD1;
    Controlador_FRM_LoginUsuario controlador_FRM_LoginUsuario;
    MetodosUsuario metodosUsuario;
    XML_Usuarios xML_Usuarios;
    Manejador_Ventanas manejador_Ventanas;
    
    
    
    /**
     * Constructor de la clase
     */
    public FRM_LoginUsuario(String sistemaInformacion, MetodosConexionBD1 metodosConexionBD1, Manejador_Ventanas manejador_Ventanas, MetodosUsuario metodosUsuario, FRM_MantenimientoUsuarios fRM_MantenimientoUsuarios) {
        
        initComponents();
        setLocation(450, 200);
        this.fRM_MantenimientoUsuarios = fRM_MantenimientoUsuarios;
        xML_Usuarios = new XML_Usuarios(fRM_MantenimientoUsuarios);
        this.metodosUsuario = metodosUsuario;
        this.manejador_Ventanas = manejador_Ventanas;
        this.metodosConexionBD1 = metodosConexionBD1;
        this.sistemaInformacion = sistemaInformacion;
        
//        controlador_FRM_LoginUsuario = new Controlador_FRM_LoginUsuario(this, this.sistemaInformacion, this.metodosConexionBD1);
        agregarEventoBtn();
        
    }
    
    /*
    Agrega las funciones al botón
    */
    public void agregarEventoBtn() {
        this.jB_Entrar.addActionListener(controlador_FRM_LoginUsuario);
    }
    
    
    /*
    Método que extrae los datos de los campos
    */
    public String getInfoPass() {
        
        char[] arrayC = this.jP_Contrasena.getPassword();
        String pass = new String(arrayC);
        
        return pass;
        
    }
    
    public String getUsuario() {
        
        String user = this.jT_Usuario.getText();
        return user;
        
    }
    
    public void limpiarCampos() {
        this.jT_Usuario.setText("");
        this.jP_Contrasena.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_Entrar = new javax.swing.JButton();
        jL_Usuario = new javax.swing.JLabel();
        jL_Contrasena = new javax.swing.JLabel();
        jT_Usuario = new javax.swing.JTextField();
        jP_Contrasena = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jB_Entrar.setBackground(new java.awt.Color(0, 192, 243));
        jB_Entrar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jB_Entrar.setText("Entrar al Sistema");
        jB_Entrar.setActionCommand("Entrar");
        jB_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_EntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jB_Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 162, 178, -1));

        jL_Usuario.setFont(new java.awt.Font("Impact", 2, 12)); // NOI18N
        jL_Usuario.setText("Usuario");
        getContentPane().add(jL_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 82, 40, -1));

        jL_Contrasena.setFont(new java.awt.Font("Impact", 2, 12)); // NOI18N
        jL_Contrasena.setText("Contraseña");
        getContentPane().add(jL_Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 128, 60, -1));
        getContentPane().add(jT_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 76, 87, -1));
        getContentPane().add(jP_Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 122, 87, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoLogin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_EntrarActionPerformed
        // TODO add your handling code here:
        switch(this.sistemaInformacion) {
            
            //En caso que fuera "ArchivosPlanos"
            case "ArchivosPlanos":
                
                

                break;
                
            //En caso que fuera archivosXML
            case "XML":

                if(xML_Usuarios.metodoLoginUsuario(getUsuario()) && xML_Usuarios.metodoLoginContrasena(getInfoPass())) {
                    this.setVisible(false);
                    this.manejador_Ventanas.mostrarFRM_MenuPrincipal();
                }else {
                    JOptionPane.showMessageDialog(null, "El usuario o la contraseña son incorrectas", "Universidad de Costa Rica", JOptionPane.INFORMATION_MESSAGE);
                    limpiarCampos();
                }
                
                break;
            
            //En caso que fuera Bases_de_Datos
            case "Bases_de_Datos":

                if(metodosConexionBD1.metodoLogin(getUsuario(), getInfoPass()))
                {
                    this.setVisible(false);
                    this.manejador_Ventanas.mostrarFRM_MenuPrincipal();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "El usuario o la contraseña son incorrectas", "Universidad de Costa Rica", JOptionPane.INFORMATION_MESSAGE);
                    limpiarCampos();
                }
                
                break;
                
        }//Fin del switch
    }//GEN-LAST:event_jB_EntrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Entrar;
    private javax.swing.JLabel jL_Contrasena;
    private javax.swing.JLabel jL_Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jP_Contrasena;
    private javax.swing.JTextField jT_Usuario;
    // End of variables declaration//GEN-END:variables
}
